### ISSUE TITLE
Repository List Method Tests

### ISSUE THREAD

**Issue by poppabear8883** [indiehd/velkart#11]
Testing `BaseEloquentRepository` is abstract so consider using 
`$this->getMockForAbstractClass('AbstractClass');`

Should include the following:

- [x] It can sort in `ascending` order
- [x] It can sort in `desc` order
- [x] It should `fail` when a random string is passed as the sort argument
- [ ] ~~It should `fail` when a random string is passed to the orderBy argument~~

Should also consider a test with passing no arguments and removing them from the repository specific tests ?

**Comment by cbj4074** [comment]
As it turns-out, the last condition cannot be tested reliably because the SQLite PDO driver in PHP not only ignores an invalid (non-existent) column reference in `ORDER BY ...`, (i.e., an exception is not thrown), but it actually returns all existing rows!

In other words, this returns all records in the table, even when the `products.foo` column does not exist:

```sql
SELECT * from products ORDER BY foo;
```

There seems to be no valid explanation for this behavior beyond it being a glaring bug.
